---
name: Exception-Class-TryCatch
version: 1.11
author:
  - 'David Golden <dagolden@cpan.org>'
abstract: Syntactic tryE<sol>catch sugar for use with Exception::Class
license: apache
resources:
  license: http://apache.org/licenses/LICENSE-2.0
requires:
  Exception::Class: 1.2
  perl: 5.005
build_requires:
  Test::More: 0.47
provides:
  Exception::Class::TryCatch:
    file: lib/Exception/Class/TryCatch.pm
    version: 1.11
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - examples
    - inc
    - t
